### ISSUE TITLE
Problem with "billing_invoice_recurring_item_add" (function malformed)

### ISSUE THREAD

**Issue by FrBillyD** [natanfelles/codeigniter-ispconfig#1]
Hi, i've found an issue with your code. Is very helpfull and i'm happy to debug-it !

The problem is in the "billing_invoice_recurring_item_add" function in the library : 
- Params array index "vat" need to be replaced by "invoice_vat_rate_id" ;
- Param "client_id" need to be add the params array as index "client_id" ;

I've only found theses two issues for the moment. Thank you for you work !

**Comment by natanfelles** [comment]
Thanks for contact. 

At the moment I am working in a new release to this library compatible with ISPConfig 3.1.

This current project was tested just by me and then can have some bugs.

Because the file is too large I decided to separate the functions in ISPConfig modules with a main file and others in a folder.

**Comment by FrBillyD** [comment]
No problem. I understood. I also use some times to write a code and i'm not always on it. In case, i give help when i can and when a project is interesting. Thank you again for your work.
Note : This project work in 3.1 for some parts 😄

**Comment by natanfelles** [comment]
Hello. I created a new branch (v-2). This is under development.

**Comment by natanfelles** [comment]
If you use PhpStorm you can use this file https://github.com/natanfelles/codeigniter-phpstorm/blob/master/phpstorm.php to help in code-completion.

**Comment by natanfelles** [comment]
Waiting for Pull Requests.
